name: Deploy MkDocs to GitHub Pages (gh-pages)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build site
        run: |
          pip install --upgrade pip
          pip install mkdocs-material mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin
          mkdocs build --strict
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: docs.baolabs.io
